In [7]:
import pandas as pd
import numpy as np

Пусть акция стоит 600\\$. На рынке можно купить европейский Call опцион со Strike price
X = 580\$ по цене 30\\$ с погашением через T = 1 год. У Васи, Пети и Коли есть вера и 600\\$ у
каждого, они хотят вложиться в эти акции. Посчитайте результаты их инвестиций (абсолютные
и в процентах), если Вася купит только один опцион, Петя - одну акцию, Коля - опционы на
все деньги, и цена акции через год будет

- 560\\$  
- 590\\$  
- 600\\$  
- 630\\$  
- 670\\$

In [30]:

import numpy as np
import plotly.express as ex
import pandas as pd


def ex_1():
    """Задание 1"""
    money = 600
    strike_price = 580
    euro_call = 30
    spot_prices = [560, 590, 600, 630, 670]

    
    x = strike_price
    vasya = np.array([v_investment(x, s, euro_call) for s in spot_prices])
    # значения для Пети
    petya =  np.array([p_investment(s1, money) for s1 in spot_prices])
    # значения для Коли
    kolya = np.array([k_investment(x,s,euro_call) for s in spot_prices])
    # Совместные результаты
    result_absolute = vasya + petya + kolya
    result_relative  = np.round(100 * result_absolute / (3 * money),2)
    book = {'Цена акции': spot_prices,
            'Вася - 1 опцион': vasya,
            'Петя - 1 акция': petya,
            'Коля - опционы на все': kolya,
            'Совместный абсолютный результат': result_absolute,
            'Совместный относительный результат, %': result_relative}
    return pd.DataFrame(book)

# Инвестиция Васи в опцион
def v_investment(strike, spot, euro_call):
    return max(spot - strike, 0) - euro_call


# Инвестиция Пети в акции
def p_investment(currnet_price, price):
    return currnet_price - price


# Инвестиция Коли в опционы на все деньги (800$) 
def k_investment(spot, strike, euro_call):
    # Сколько опционов может купить Коля на суммы spot (800$)
    option_count = spot / euro_call
    return option_count * (max(spot - strike, 0) - euro_call)

### Изначальная стоимость акции 600$

In [31]:
ex_1()

,Цена акции,Вася - 1 опцион,Петя - 1 акция,Коля - опционы на все,Совместный абсолютный результат,"Совместный относительный результат, %"
0,560,-30,-40,-193.333333,-263.333333,-14.63
1,590,-20,-10,-580.000000,-610.000000,-33.89
2,600,-10,0,-580.000000,-590.000000,-32.78
3,630,20,30,-580.000000,-530.000000,-29.44
4,670,60,70,-580.000000,-450.000000,-25.00

In [33]:
money = 600
strike_price = 580
euro_call = 30
prices = np.array([560, 590, 600, 630, 670])


def vasya_result(x, s, euro_call):
        return max(s-x, 0) - euro_call


def petya_result(s1, s0):
        return s1 - s0


def kolya_result(x, s, euro_call):
        return (money/euro_call) * (max(s - x, 0) - euro_call)

# Задание 1. Результаты инвести
def exercise_1(s0, x, euro_call, spot_prices: np.array) -> pd.DataFrame:
        # значения для Васи
        vasya = np.array([vasya_result(x, s, euro_call) for s in spot_prices])
        # значения для Пети
        petya =  np.array([petya_result(s1, s0) for s1 in spot_prices])
        # значения для Коли
        kolya = np.array([kolya_result(x,s,euro_call) for s in spot_prices])

        # Совместные результаты
        result_absolute = vasya + petya + kolya
        result_relative  = np.round(100 * result_absolute / (3 * s0),2)

        book = {'Цена акции': spot_prices,
                'Вася': vasya,
                'Петя': petya,
                'Коля': kolya,
                'Совместный абсолютный результат': result_absolute,
                'Совместный относительный результат, %': result_relative}
        return pd.DataFrame(book)

exercise_1(money, strike_price,euro_call,prices)

,Цена акции,Вася,Петя,Коля,Совместный абсолютный результат,"Совместный относительный результат, %"
0,560,-30,-40,-600.0,-670.0,-37.22
1,590,-20,-10,-400.0,-430.0,-23.89
2,600,-10,0,-200.0,-210.0,-11.67
3,630,20,30,400.0,450.0,25.00
4,670,60,70,1200.0,1330.0,73.89